server:
  port: 8081
  
logging:
 file:
  name: logs/studentapp-dev.log
 pattern:
  file: "%d %-5level [%thread] %logger:%msg%n"
 level:
    '[org.springframework.web]': INFO
    '[org.hibernate]': INFO
    '[com.tpe]': INFO
    
management:
  endpoints:
    web:
      exposure:
        include: ['trace', 'auditevents', 'threddump', 'configprops', 'health', 'env', 'metrics', 'logfile', 'loggers', 'beans']
        